name: Notifier

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:

      - name: Gitleaks
        uses: zricethezav/gitleaks-action@v1
        id: gitleaks
        with:
          # Path to config (relative to $GITHUB_WORKSPACE)
          config-path: default

      - name: Telegram Notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            Repository: ${{ github.repository }}
            Gitleaks: ${{ join(steps.gitleaks.outputs.*, '\n') }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
